#!/usr/bin/env bash

function print_help {
cat <<EOF
Description here
etc
EOF
}
 

case $1 in
    h) print_help ; exit  ;;
esac

$HOME/tools/arduino-1.8.7/arduino --upload atlast.c --port /dev/ttyUSB*
