#!/usr/bin/env bash

# connect.sh

# Usage:
# $ connect.sh <device> <port speed>
# Example: connect.sh /dev/ttyS0 9600

function foo ()
{
	./connect.sh /dev/ttyACM0 9600 <<EOF
!20190101010101010
EOF
}

#foo
#exit

DS=`date --utc +%Y%m%d%H%M%S`
CMD="\n!$DS\n"

DEV=/dev/ttyACM0
stty -F $DEV 9600
#cat $DEV &
#bgPid=$!
#echo $CMD
echo -e "?" >$DEV
#echo "" > $DEV
#kill $bgPid
exit
