#!/bin/sh

# connect.sh

# Usage:
# $ connect.sh <device> <port speed>
# Example: connect.sh /dev/ttyS0 9600

DS=`date --utc +%Y%m%d%H%M%S`
CMD="!$DS"

socat - /dev/ttyACM0 <<EOF


$CMD
EOF
exit

DEV=/dev/ttyACM0
stty -F $DEV 9600
#cat $DEV &
#bgPid=$!
#echo $CMD
echo  $CMD >$DEV
#echo "" > $DEV
#kill $bgPid
#./connect.sh /dev/ttyACM0 9600 <<EOF
#!20190101010101010
#EOF
exit
